version: '3.1'

services:
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/app